// Dashboard Components - Export all components for easier imports

export { default as WelcomeModal } from './WelcomeModal'
export { default as ProgressTracker } from './ProgressTracker'
export { default as LessonPlayer } from './LessonPlayer'
export { default as LessonNavigationBar } from './LessonNavigationBar'
export { default as MemberNavigation } from './MemberNavigation'
export { default as ContinueYourPath } from './ContinueYourPath'
export { default as DiscoverMore } from './DiscoverMore'
export { default as CourseOutline } from './CourseOutline'
export { default as LessonNotes } from './LessonNotes'
export { default as LessonNotesPanel } from './LessonNotesPanel'
export { default as LessonControls } from './LessonControls'
export { default as AchievementBadge, AchievementCelebration } from './AchievementBadge'
export { default as AchievementsDisplay } from './AchievementsDisplay'
export { default as StreakCalendar } from './StreakCalendar'
export { default as Toast } from './Toast'
export { default as DashboardSearch } from './DashboardSearch'
export { default as LessonRecommendations } from './LessonRecommendations'
export { default as RelatedLessons } from './RelatedLessons'
export { default as SkeletonLoader } from './SkeletonLoader'
export { default as AdvancedAnalytics } from './AdvancedAnalytics'
export { default as ProgressCharts } from './ProgressCharts'
export { default as MasteryChart } from './MasteryChart'
export { useKeyboardShortcuts, KeyboardShortcutsHelp } from './KeyboardShortcuts'
export { default as LearningPathVisualization } from './LearningPathVisualization'
export { default as LearningPathTimeline } from './LearningPathTimeline'
export { default as LearningPathGraph } from './LearningPathGraph'
export { default as ProgressHeatmap } from './ProgressHeatmap'
export { default as SelfPacedReminder } from './SelfPacedReminder'

